<?php

declare(strict_types=1);

use App\Enums\CourseLevelEnum;

return [
    'real_data' => [
        [
            'title' => 'Laravel 12 & Livewire: The Full Stack Guide',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Master the latest Laravel features and build high-performance reactive interfaces without leaving PHP.',
            'lessons' => [
                'Environment Setup with Herd & Bun',
                'Understanding the Directory Structure',
                'Eloquent Relationships: One to Many',
                'Building Interactive Components with Flux',
                'Real-time Validation & Flash Messages',
                'Deploying to Laravel Forge',
            ],
        ],
        [
            'title' => 'Mastering Tailwind CSS 4.0',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Learn how to build modern, responsive landing pages using the utility-first workflow of Tailwind CSS.',
            'lessons' => [
                'The New Zero-Config Engine',
                'Container Queries & Dynamic Grids',
                'Advanced Hover & Group States',
                'Dark Mode & Semantic Theming',
                'Extracting Reusable Blade Components',
            ],
        ],
        [
            'title' => 'Docker & Kubernetes for PHP Developers',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Take your DevOps skills to the next level by containerizing your PHP workflow.',
            'lessons' => [
                'Dockerizing a Laravel Application',
                'Managing Multi-Container Environments',
                'Optimization: Multi-stage Builds',
                'Kubernetes Pods and Deployments',
                'CI/CD Pipelines with GitHub Actions',
            ],
        ],
        [
            'title' => 'Clean Code & Design Patterns in PHP 8.4',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Learn the architectural patterns used by senior developers to write maintainable software.',
            'lessons' => [
                'The SOLID Principles Explained',
                'Implementing the Repository Pattern',
                'Dependency Injection & Service Containers',
                'Writing Testable Code with Pest',
                'Refactoring Legacy Applications',
            ],
        ],
        [
            'title' => 'Advanced Eloquent: Beyond CRUD',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Master complex database interactions, custom collections, and performance optimization in Laravel.',
            'lessons' => [
                'Query Scopes and Global Scopes',
                'Mastering Many-to-Many Relationships',
                'Polymorphic Relationships in Depth',
                'Efficient Eager Loading & Lazy Loading',
                'Using Database Views with Eloquent',
                'Implementing Observers and Events',
            ],
        ],
        [
            'title' => 'Alpine.js for Reactive UIs',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Build modern, interactive interfaces with a fraction of the code required by larger frameworks.',
            'lessons' => [
                'The Alpine Lifecycle',
                'State Management with x-data',
                'Handling Events and Modifiers',
                'Animations with x-transition',
                'Integrating with Livewire Components',
            ],
        ],
        [
            'title' => 'Unit Testing with Pest PHP',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Learn the elegant testing framework that makes writing tests a joy for Laravel developers.',
            'lessons' => [
                'Introduction to Expectation API',
                'Testing Eloquent Models',
                'Mocking External Services',
                'Architecture Testing in Pest',
                'Data Sets and Higher Order Testing',
            ],
        ],
        [
            'title' => 'Mastering Redis with Laravel',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Scale your application using high-performance caching, pub/sub, and real-time queues.',
            'lessons' => [
                'Redis Data Types Explained',
                'Advanced Caching Strategies',
                'Rate Limiting with Redis',
                'Real-time Notifications via Pub/Sub',
                'Atomic Locks and Concurrency',
            ],
        ],
        [
            'title' => 'Full-Stack Deployment with Kamal',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Deploy your web applications to any cloud provider with zero-downtime using Kamal.',
            'lessons' => [
                'The Kamal Architecture',
                'Configuring your Servers',
                'Deploying your First App',
                'Handling Secrets and Environment Vars',
                'Rollbacks and Health Checks',
            ],
        ],
        [
            'title' => 'API Development with Laravel Sanctum',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Secure your mobile and single-page applications with token-based authentication.',
            'lessons' => [
                'Sanctum vs. Passport',
                'Issuing Personal Access Tokens',
                'SPA Authentication with Cookies',
                'Mobile App Auth Workflow',
                'Revoking Tokens and Security best practices',
            ],
        ],
        [
            'title' => 'PostgreSQL for Laravel Developers',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Go beyond the basics and leverage JSONB, Full-text search, and window functions.',
            'lessons' => [
                'Working with JSONB Columns',
                'Full-Text Search Implementation',
                'PostGIS for Geographic Data',
                'Performance Tuning and Indexing',
                'Lateral Joins and CTEs',
            ],
        ],
        [
            'title' => 'TypeScript for React Developers',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Eliminate runtime errors by bringing static typing to your React applications.',
            'lessons' => [
                'Interfaces vs. Types',
                'Typing Props and State',
                'Using Generics in Components',
                'External Library Typings',
                'Advanced Utility Types',
            ],
        ],
        [
            'title' => 'Building SaaS with Stripe and Laravel Cashier',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Implement subscriptions, one-time payments, and customer portals easily.',
            'lessons' => [
                'Stripe Integration Fundamentals',
                'Setting up Subscription Plans',
                'Handling Webhooks and Failed Payments',
                'Generating Invoices and Tax Support',
                'Creating a Customer Billing Portal',
            ],
        ],
        [
            'title' => 'Infrastructure as Code with Terraform',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Manage your cloud infrastructure across AWS, DigitalOcean, and GCP using code.',
            'lessons' => [
                'Providers and Resources',
                'State Management and Backends',
                'Module Patterns for Reusability',
                'Variables and Output Values',
                'Terraform Plan and Apply Workflows',
            ],
        ],
        [
            'title' => 'Python for Data Science Fundamentals',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'The essential Python toolkit for analyzing data and building machine learning models.',
            'lessons' => [
                'NumPy for Numerical Computing',
                'Pandas DataFrames and Series',
                'Data Cleaning and Preparation',
                'Visualization with Matplotlib',
                'Statistical Analysis with SciPy',
            ],
        ],
        [
            'title' => 'Microservices Architecture with Go',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Build scalable, concurrent microservices using the Go programming language.',
            'lessons' => [
                'Go Concurrency and Goroutines',
                'Implementing gRPC Communication',
                'Service Discovery and API Gateways',
                'Distributed Tracing and Logging',
                'Dockerizing Go Microservices',
            ],
        ],
        [
            'title' => 'Building Native Apps with React Native',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Use your React skills to build native iOS and Android applications.',
            'lessons' => [
                'Native Components vs Web Elements',
                'Navigation with React Navigation',
                'Handling Touch Events and Gestures',
                'Integrating Native Device Features',
                'Publishing to App Stores',
            ],
        ],
        [
            'title' => 'Machine Learning with Scikit-Learn',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Implement predictive models using classification, regression, and clustering algorithms.',
            'lessons' => [
                'Supervised vs Unsupervised Learning',
                'Feature Engineering and Selection',
                'Model Evaluation and Cross-Validation',
                'Hyperparameter Tuning with GridSearch',
                'Pipelines for Automated Workflows',
            ],
        ],
        [
            'title' => 'Mastering Git and GitHub Workflows',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'The definitive guide to version control and collaborating on professional software teams.',
            'lessons' => [
                'Branching and Merging Strategies',
                'Handling Merge Conflicts like a Pro',
                'Interactive Rebasing and Cherry-Picking',
                'GitHub Actions for CI/CD',
                'Pull Request Best Practices',
            ],
        ],
        [
            'title' => 'Advanced CSS Grid and Flexbox Layouts',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Create complex, responsive web layouts without relying on heavy frameworks.',
            'lessons' => [
                'Grid Template Areas and Naming',
                'Responsive Design without Media Queries',
                'Alignment and Distribution Patterns',
                'Subgrid and Parent-Child Relationships',
                'Modern CSS Selectors and Functions',
            ],
        ],
        [
            'title' => 'Node.js Backend Essentials with NestJS',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Build enterprise-grade Node.js applications with a structured, modular approach.',
            'lessons' => [
                'Modules, Controllers, and Services',
                'Dependency Injection in NestJS',
                'Validation with Pipes and DTOs',
                'Database Integration with TypeORM',
                'Building Real-time Apps with WebSockets',
            ],
        ],
        [
            'title' => 'GraphQL API Design with Apollo',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Design flexible and efficient APIs that give clients exactly the data they need.',
            'lessons' => [
                'Schema Definitions and Resolvers',
                'Queries, Mutations, and Subscriptions',
                'Data Fetching and Caching Strategies',
                'Error Handling and Security in GraphQL',
                'Integrating with React and Vue Clients',
            ],
        ],
        [
            'title' => 'Cybersecurity Fundamentals for Developers',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Learn how to identify and prevent common web vulnerabilities like XSS and SQLi.',
            'lessons' => [
                'The OWASP Top 10 Risks',
                'Secure Password Hashing and Storage',
                'Cross-Site Scripting (XSS) Prevention',
                'Cross-Site Request Forgery (CSRF)',
                'Encryption and Data Protection Basics',
            ],
        ],
        [
            'title' => 'Effective Technical Writing for Engineers',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Improve your career by communicating complex technical ideas clearly and concisely.',
            'lessons' => [
                'Writing Clear READMEs and Documentation',
                'Structuring Technical Proposals',
                'Communicating with Non-Technical Stakeholders',
                'Blogging for Personal Branding',
                'Editing and Peer Review Techniques',
            ],
        ],
        [
            'title' => 'Building Real-time Dashboards with Livewire',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Create interactive analytics dashboards that update instantly without page reloads.',
            'lessons' => [
                'Livewire Polling and Refreshing',
                'Integrating Chart.js with Livewire',
                'Filtering Large Datasets in Real-time',
                'Exporting Data to CSV and PDF',
                'Optimizing Performance for High Traffic',
            ],
        ],
        [
            'title' => 'SEO Best Practices for Web Developers',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Ensure your web applications are discoverable and rank high in search engine results.',
            'lessons' => [
                'Semantic HTML and Accessibility',
                'Optimizing Core Web Vitals',
                'Metadata and Open Graph Tags',
                'Sitemaps and Robots.txt Configuration',
                'Structured Data with Schema.org',
            ],
        ],
        [
            'title' => 'Introduction to Functional Programming in JS',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Write cleaner, more predictable code by mastering functional programming concepts.',
            'lessons' => [
                'Pure Functions and Immutability',
                'Map, Filter, and Reduce in Action',
                'Function Composition and Currying',
                'Handling Side Effects with Monads',
                'Implementing FP in Modern Frameworks',
            ],
        ],
        [
            'title' => 'Serverless Functions with AWS Lambda',
            'level' => CourseLevelEnum::ADVANCED,
            'description' => 'Build and scale backend logic without managing any servers using AWS Lambda.',
            'lessons' => [
                'Triggering Functions with API Gateway',
                'Connecting to DynamoDB and S3',
                'Handling Cold Starts and Performance',
                'Testing and Monitoring Serverless Apps',
                'Cost Optimization for Lambda',
            ],
        ],
        [
            'title' => 'Building Progressive Web Apps (PWAs)',
            'level' => CourseLevelEnum::INTERMEDIATE,
            'description' => 'Transform your web apps into native-like experiences with offline support and installability.',
            'lessons' => [
                'Service Workers and Caching Strategies',
                'Web App Manifest Configuration',
                'Handling Push Notifications',
                'Offline Data Syncing with IndexedDB',
                'Optimizing Performance for Mobile Devices',
            ],
        ],
        [
            'title' => 'Mastering Vue 3 with the Composition API',
            'level' => CourseLevelEnum::BEGINNER,
            'description' => 'Learn the modern way to build reusable and maintainable components in Vue 3.',
            'lessons' => [
                'Setup Function and Reactive Refs',
                'Computed Properties and Watchers',
                'Lifecycle Hooks in Composition API',
                'Building Custom Composables',
                'Integrating with Pinia for State Management',
            ],
        ],
    ],
    'video_urls' => [
        'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-720p.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    ],
];
